//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallDevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstallDevice()
        {
            this.Adress = new HashSet<Adress>();
            this.ListPhone1 = new HashSet<ListPhone>();
        }
    
        public int ID { get; set; }
        public string NameDevice { get; set; }
        public int TypeDevice { get; set; }
        public string SerialNumber { get; set; }
        public int Port { get; set; }
        public string MAC { get; set; }
        public string IP { get; set; }
        public Nullable<int> IDAdress { get; set; }
        public string Gatevay { get; set; }
        public Nullable<int> ListPhone { get; set; }
        public Nullable<System.DateTime> DateInstalling { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adress> Adress { get; set; }
        public virtual PortType PortType { get; set; }
        public virtual TypeDevice TypeDevice1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListPhone> ListPhone1 { get; set; }
    }
}
