//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListPhone
    {
        public int ID { get; set; }
        public int Gateway { get; set; }
        public string LinePhone { get; set; }
    
        public virtual GatewayPhone GatewayPhone { get; set; }
        public virtual InstallDevice InstallDevice { get; set; }
    }
}
