//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public int ID { get; set; }
        public int IDRole { get; set; }
        public string Event { get; set; }
        public Nullable<System.DateTime> DataEvent { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
