//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassportInfo
    {
        public int ID { get; set; }
        public string Series { get; set; }
        public string Number { get; set; }
        public System.DateTime DateIssue { get; set; }
        public string WhomIssue { get; set; }
        public string Code { get; set; }
    }
}
