//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subsriber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subsriber()
        {
            this.ApplicationCRM = new HashSet<ApplicationCRM>();
            this.ConectedService = new HashSet<ConectedService>();
        }
    
        public int ID { get; set; }
        public string NumberSub { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronumic { get; set; }
        public int CodeGender { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string NumberContract { get; set; }
        public string Email { get; set; }
        public string AdressUser { get; set; }
        public int District { get; set; }
        public string FactAdress { get; set; }
        public string SeriasNumber { get; set; }
        public string Code { get; set; }
        public string WhomIssue { get; set; }
        public System.DateTime DateIssue { get; set; }
        public string Contract { get; set; }
        public System.DateTime DateCreateContract { get; set; }
        public int TypeContract { get; set; }
        public string ReasonForTermination { get; set; }
        public string PersonalAccount { get; set; }
        public Nullable<System.DateTime> DateTermination { get; set; }
        public Nullable<System.DateTime> Rent { get; set; }
        public Nullable<int> SerialNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationCRM> ApplicationCRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConectedService> ConectedService { get; set; }
        public virtual ContractType ContractType { get; set; }
        public virtual Device Device { get; set; }
        public virtual District District1 { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
